import "../styles/index.css";

import type { AppProps } from "next/app";
import { QueryClient, QueryClientProvider } from "react-query";
import Head from "next/head";
import Navigation from "../components/Navigation/Navigation";

const queryClient = new QueryClient();

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <QueryClientProvider client={queryClient}>
      <div>
        <Head>
          <title>Finance API</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Navigation />
          <Component {...pageProps} />
        </main>
      </div>
    </QueryClientProvider>
  );
}
export default MyApp;
